# Generated by Django 4.0.5 on 2022-12-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_entry_updated',
            name='diff',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
