# Generated by Django 4.0.5 on 2023-02-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0003_alter_client_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.JSONField(),
        ),
    ]
