# Generated by Django 4.0.5 on 2023-01-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0003_client_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avator',
            field=models.ImageField(auto_created='media/default_image.png', upload_to='avator'),
        ),
    ]
