# Generated by Django 4.0.5 on 2023-01-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0004_alter_client_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avator',
            field=models.ImageField(null=True, upload_to='avator'),
        ),
    ]
