# Generated by Django 4.0.5 on 2023-02-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0005_alter_entry_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(default=1)),
            ],
        ),
    ]
