# Generated by Django 4.0.5 on 2023-03-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0007_tags_create_date_tags_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
